"""initial schema

Revision ID: 125a4337b000
Revises: 
Create Date: 2026-04-11 17:01:18.647801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '125a4337b000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'opportunity_applicant_types', 'opportunities', ['opportunity_id'], ['id'])
    op.create_foreign_key(None, 'opportunity_categories', 'opportunities', ['opportunity_id'], ['id'])
    op.create_foreign_key(None, 'opportunity_documents', 'opportunities', ['opportunity_id'], ['id'])
    op.create_foreign_key(None, 'saved_opportunities', 'opportunities', ['opportunity_id'], ['id'])
    op.add_column('scraped_grants', sa.Column('combined_text', sa.Text(), nullable=True))
    op.add_column('scraped_grants', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # Add created_at as nullable first (can't add NOT NULL to existing rows)
    op.add_column('scraped_grants', sa.Column('created_at', sa.DateTime(), nullable=True))
# Fill existing rows with loaded_at timestamp (or current time)
    op.execute("UPDATE scraped_grants SET created_at = COALESCE(loaded_at, NOW()) WHERE created_at IS NULL")
# Now make it NOT NULL
    op.alter_column('scraped_grants', 'created_at', nullable=False)
    op.alter_column('scraped_grants', 'state',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),   
               existing_nullable=True)
    op.alter_column('scraped_grants', 'summary',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('scraped_grants', 'source_file',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('scraped_grants', 'content_hash',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_scraped_grants_content_hash'), 'scraped_grants', ['content_hash'], unique=False)
    op.create_index(op.f('ix_scraped_grants_id'), 'scraped_grants', ['id'], unique=False)
    # Add scraper_name as nullable first, fill with default, then make NOT NULL
    op.add_column('scraper_runs', sa.Column('scraper_name', sa.String(length=200), nullable=True))
    op.execute("UPDATE scraper_runs SET scraper_name = 'legacy_scraper' WHERE scraper_name IS NULL")
    op.alter_column('scraper_runs', 'scraper_name', nullable=False)

# Add started_at as nullable first, fill with created_at, then make NOT NULL  
    op.add_column('scraper_runs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE scraper_runs SET started_at = created_at WHERE started_at IS NULL")
    op.alter_column('scraper_runs', 'started_at', nullable=False)
    
    op.add_column('scraper_runs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('scraper_runs', sa.Column('grants_found', sa.Integer(), nullable=True))
    op.add_column('scraper_runs', sa.Column('grants_new', sa.Integer(), nullable=True))
    op.add_column('scraper_runs', sa.Column('grants_updated', sa.Integer(), nullable=True))
    op.add_column('scraper_runs', sa.Column('grants_errors', sa.Integer(), nullable=True))
    op.alter_column('scraper_runs', 'run_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('scraper_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('scraper_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_scraper_runs_created_at', table_name='scraper_runs')
    op.drop_index('idx_scraper_runs_run_id', table_name='scraper_runs')
    op.create_index(op.f('ix_scraper_runs_created_at'), 'scraper_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scraper_runs_id'), 'scraper_runs', ['id'], unique=False)
    op.create_index(op.f('ix_scraper_runs_run_id'), 'scraper_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_scraper_runs_started_at'), 'scraper_runs', ['started_at'], unique=False)
    op.drop_column('scraper_runs', 'records_scraped')
    op.drop_column('scraper_runs', 'state_name')
    op.drop_column('scraper_runs', 'attempt')
    op.drop_column('scraper_runs', 'state_code')
    op.drop_column('scraper_runs', 'run_type')
    op.drop_column('scraper_runs', 'duration_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraper_runs', sa.Column('duration_seconds', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('scraper_runs', sa.Column('run_type', sa.VARCHAR(length=20), server_default=sa.text("'scheduled'::character varying"), autoincrement=False, nullable=True))
    op.add_column('scraper_runs', sa.Column('state_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('scraper_runs', sa.Column('attempt', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('scraper_runs', sa.Column('state_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('scraper_runs', sa.Column('records_scraped', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_scraper_runs_started_at'), table_name='scraper_runs')
    op.drop_index(op.f('ix_scraper_runs_run_id'), table_name='scraper_runs')
    op.drop_index(op.f('ix_scraper_runs_id'), table_name='scraper_runs')
    op.drop_index(op.f('ix_scraper_runs_created_at'), table_name='scraper_runs')
    op.create_index('idx_scraper_runs_run_id', 'scraper_runs', ['run_id'], unique=False)
    op.create_index('idx_scraper_runs_created_at', 'scraper_runs', [sa.text('created_at DESC')], unique=False)
    op.alter_column('scraper_runs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scraper_runs', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('scraper_runs', 'run_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('scraper_runs', 'grants_errors')
    op.drop_column('scraper_runs', 'grants_updated')
    op.drop_column('scraper_runs', 'grants_new')
    op.drop_column('scraper_runs', 'grants_found')
    op.drop_column('scraper_runs', 'completed_at')
    op.drop_column('scraper_runs', 'started_at')
    op.drop_column('scraper_runs', 'scraper_name')
    op.drop_index(op.f('ix_scraped_grants_id'), table_name='scraped_grants')
    op.drop_index(op.f('ix_scraped_grants_content_hash'), table_name='scraped_grants')
    op.alter_column('scraped_grants', 'content_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('scraped_grants', 'source_file',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('scraped_grants', 'summary',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scraped_grants', 'state',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('scraped_grants', 'created_at')
    op.drop_column('scraped_grants', 'logo_url')
    op.drop_column('scraped_grants', 'combined_text')
    op.drop_constraint(None, 'saved_opportunities', type_='foreignkey')
    op.drop_constraint(None, 'opportunity_documents', type_='foreignkey')
    op.drop_constraint(None, 'opportunity_categories', type_='foreignkey')
    op.drop_constraint(None, 'opportunity_applicant_types', type_='foreignkey')
    # ### end Alembic commands ###
